### ISSUE TITLE
When resetting the password, the new password can be set to empty.

### ISSUE THREAD

**Issue by LuckyZY** [filerun/docker#55]
I'm really sorry for my poor English, I used google translate tool to translate

the problem i'm having：

After entering Filerun, click the avatar in the lower left corner to reset the password. At this time, Google browser will automatically fill in the password. At this time, I do not choose to fill in a new password in the reset password dialog box. Clicking Save will still take effect. The new password was set to empty, which made it impossible to log in to Filerun again.

**Comment by filerun** [comment]
Thank you for reporting this.
I confirm the problem. At least is limited only to the FileRun supeuser accounts, for which the password policy does not apply.
Please use this guide to reset access for the FileRun superuser: https://docs.filerun.com/resetting_the_superuser_password
The problem will be fixed with the upcoming FileRun update.
